// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.0
// LVGL version: 8.3.6
// Project name: time_music_2

#ifndef _TIME_MUSIC_2_UI_H
#define _TIME_MUSIC_2_UI_H

#ifdef __cplusplus
extern "C" {
#endif

#include "lvgl.h"

#include "ui_helpers.h"
#include "ui_events.h"

void lyrics_ami_Animation(lv_obj_t * TargetObject, int delay);
// SCREEN: ui_Screen1
void ui_Screen1_screen_init(void);
extern lv_obj_t * ui_Screen1;
extern lv_obj_t * ui_Label2;
extern lv_obj_t * ui_Label1;
extern lv_obj_t * ui_Label4;
void ui_event_Button1(lv_event_t * e);
extern lv_obj_t * ui_Button1;



// SCREEN: ui_Screen2
void ui_Screen2_screen_init(void);
extern lv_obj_t * ui_Screen2;
extern lv_obj_t * ui_Label3;
extern lv_obj_t * ui_Label5;
void ui_event_Button2(lv_event_t * e);
extern lv_obj_t * ui_Button2;
extern lv_obj_t * ui____initial_actions0;

LV_FONT_DECLARE(ui_font_MYFONT30);
LV_FONT_DECLARE(ui_font_MYFONT48);
LV_FONT_DECLARE(ui_font_Font20);
LV_FONT_DECLARE(ui_font_music38);
LV_FONT_DECLARE(ui_font_music26);

void ui_init(void);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
